### ISSUE TITLE
Database design

### ISSUE THREAD

**Issue by natalia-alarcon-azumo** [blackbookcleaner/Socialsonar#139]
Milestone: New Scope backend

Analyze and update existing database design

**Comment by natalia-alarcon-azumo** [comment]
https://github.com/social-sonar/social-sonar-api

**Comment by christian-herrera-azumo** [comment]
Updated Prisma models and added first migration related to the API

### Latest ER diagram

![Image](https://github.com/user-attachments/assets/f1bf0191-0600-462d-8ed6-a6379a6119ab)
