### ISSUE TITLE
Initialize project

### ISSUE THREAD

**Issue by natalia-alarcon-azumo** [blackbookcleaner/Socialsonar#142]
All the necessary dependencies - End First prisma migration - Basic Sentry integration

**Comment by christian-herrera-azumo** [comment]
- Added initial project structure
- Tests using jest and supertest
- Sentry integration (production)
- Other configs such as prettier and eslint
- Created repository and basic README
- Added github workflow

New repository: https://github.com/social-sonar/social-sonar-api
