### ISSUE TITLE
Authentication: mechanism for users.

### ISSUE THREAD

**Issue by natalia-alarcon-azumo** [blackbookcleaner/Socialsonar#149]
Investigation - Support for login using username and password, implementing a secure authentication mechanism for users.

**Comment by zaldivards** [comment]
I'm blocked temporarily: I need to add some configs in the apple developer platform but I don't have enough permissions

**Comment by christian-herrera-azumo** [comment]
I'm blocked temporarily: I need to add some configs in the apple developer platform but I don't have enough permissions

**Comment by christian-herrera-azumo** [comment]
PR: https://github.com/social-sonar/social-sonar-api/pull/1
