### ISSUE TITLE
Contacts status

### ISSUE THREAD

**Issue by esteban-licausi-azumo** [blackbookcleaner/Socialsonar#204]
**Description of the increment**
In this increment, we propose to change the logic of the different contacts:
-Preference: if the system finds two contacts with different names but the same number, it should display the contacts' information in the preference screen, and ask the user which one he/she prefers. Once the user clicks on the “preferred contact”, the other one is deleted.
-Duplicates: If there are two users with the same name, the system should display a message saying that they are duplicates, and allow the user to confirm for the system to merge them.

**Acceptance criteria:**
-If two users have different names but the same number they should go to the 'preference' screen.
-If two users have the same name but different numbers, the system must allow the user to confirm the merge.

**Comment by raffi-bedoyan-azumo** [comment]
PR Made in: https://github.com/social-sonar/social-sonar-api/pull/21
