### ISSUE TITLE
Review AppleID Token Expiration

### ISSUE THREAD

**Issue by esteban-licausi-azumo** [blackbookcleaner/Socialsonar#207]
Description:
Currently, the AppleID token is expiring every two days, requiring users to perform a logout/login to continue. The goal of this task is to investigate the cause of the token’s premature expiration and resolve the issue to prevent users from being forced to log out and back in so frequently.

Tasks:

	1.	Review the current implementation of AppleID authentication.
	2.	Verify the token expiration configuration.
	3.	Determine if the issue is related to token refresh settings or Apple policies.
	4.	Propose and apply a solution to extend the token validity or implement an automatic refresh flow.
	5.	Perform tests to ensure the token no longer expires prematurely.

Acceptance Criteria:

	•	Users should no longer be forced to log out and log back in every two days.
	•	The token should remain valid for the specified duration, or it should automatically refresh when necessary.

**Comment by raffi-bedoyan-azumo** [comment]
It was an issue with the HTTP Status interpreted from the client. It was an inconsistency with the interpretation of the codes 401 and 403. I already fixed it.
