### ISSUE TITLE
Appointment Scheduling Feature - Basic Calendly Features

### ISSUE THREAD

**Issue by agrasso-azumo** [blackbookcleaner/Socialsonar#43]
Implement a simplified version of Calendly with essential scheduling functionalities, designed for ease of use and efficiency.

**Comment by christian-herrera-azumo** [comment]
This is the progress so far. This is how the UI looks and part of the logic

https://github.com/blackbookcleaner/Socialsonar/assets/140095738/5daf3981-32d4-492f-a523-da3fe40e2ce5

**Comment by christian-herrera-azumo** [comment]
- Added timezone support
- Events are set in google calendar and attendees are properly notified
